name: music
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # swipeable_page_route: ^0.4.7
  # modal_bottom_sheet: ^3.0.0
  get: ^4.6.6
  dynamic_color: ^1.8.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  sliding_up_panel2: ^3.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: AliIconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf